we extensively use PyTorch for implementing our deep learning models. PyTorch is an
open source, community­driven deep learning framework. Unlike Theano, Caffe, and TensorFlow,
PyTorch implements a tape­based
a
utomatic differentiation method that allows us to define and
execute computational graphs dynamically. This is extremely helpful for debugging and also for
constructing sophisticated models with minimal effort.


PyTorch is an optimized tensor manipulation library that offers an array of packages for deep learning.
At the core of the library is the tensor, which is a mathematical object holding some multidimensional
data. A tensor of order zero is just a number, or a scalar. A tensor of order one (1st­order tensor) is an
array of numbers, or a vector. Similarly, a 2nd­order tensor is an array of vectors, or a matrix.
Therefore, a tensor can be generalized as an n­dimensional array of scalars,

In [12]:
#Creating tensors
def describe(x):
  print("Type: {}".format(x.type()))
  print("Shape/size: {}".format(x.shape))
  print("Values: \n{}".format(x))

In [13]:
import torch
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-8.8171e+21,  4.5897e-41, -8.8171e+21],
        [ 4.5897e-41,  0.0000e+00,  0.0000e+00]])


In [14]:
describe(torch.rand(2, 3)) # uniform random
describe(torch.randn(2, 3)) # random normal

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.2940, 0.5985, 0.6126],
        [0.7091, 0.0038, 0.7627]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.2617, -0.7935,  0.2861],
        [-1.6680, -1.6401,  0.1859]])


In [15]:
import torch
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [16]:
x = torch.Tensor([[1, 2, 3],
[4, 5, 6]])
describe(x)


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


The values can either come from a list, as in the preceding example, or from a NumPy array. And, of
course, we can always go from a PyTorch tensor to a NumPy array, as well. Notice that the type of the
tensor is DoubleTensor instead of the default FloatTensor (see the next section). This
corresponds with the data type of the NumPy random matrix, a float64

In [17]:
import torch
import numpy as np
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))


Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.9277, 0.2449, 0.4839],
        [0.2398, 0.6270, 0.9614]], dtype=torch.float64)


In [18]:
x = torch.FloatTensor([[1, 2, 3],
[4, 5, 6]])
describe(x)


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [19]:
x = x.long()
describe(x)


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [20]:
import torch
x = torch.randn(2, 3)
describe(x)


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.0151, -0.0132,  0.3481],
        [ 0.0766, -1.3892, -0.1397]])


In [21]:
describe(torch.add(x, x))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 2.0303, -0.0264,  0.6963],
        [ 0.1532, -2.7784, -0.2794]])


In [22]:
describe(x + x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 2.0303, -0.0264,  0.6963],
        [ 0.1532, -2.7784, -0.2794]])


In [23]:
x = torch.arange(6)
describe(x)


Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [24]:
describe(torch.sum(x, dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
15


In [26]:
import torch
x = torch.arange(6).view(2, 3)
describe(x)


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
